#!/bin/sh

user_agent='github.com/njhanley/adventofcode by nicholasjhanley@gmail.com'

die() { printf '%s\n' "$*" >&2; exit 1; }

[ "$AOC_SESSION" ] || die "AOC_SESSION is not set"

cwd="$(pwd)"
dir="${cwd##*/}"
day="${dir%%[^0-9]*}"
day="${day#0}"

cwd="${cwd%/*}"
dir="${cwd##*/}"
year="${dir%%[^0-9]*}"

curl --no-progress-meter \
     --cookie "session=$AOC_SESSION" \
     --user-agent "$user_agent" \
     "https://adventofcode.com/$year/day/$day/input" \
| tee input.txt
